2018-08-03 21:46:21,368 1 INFO ? odoo: Odoo version 11.0-20180710
2018-08-03 21:46:21,369 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2018-08-03 21:46:21,369 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/11.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
2018-08-03 21:46:21,369 1 INFO ? odoo: database: odoo@dbpsql:5432
2018-08-03 21:46:21,382 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/11.0
2018-08-03 21:46:21,382 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons
2018-08-03 21:46:21,383 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons
2018-08-03 21:46:21,837 1 INFO ? odoo.service.server: AutoReload watcher running
2018-08-03 21:46:21,841 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 75c2fb0b867a:8069
2018-08-03 21:46:21,999 1 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2018-08-03 22:02:39,560 1 INFO ? odoo.service.server: Initiating shutdown
2018-08-03 22:02:39,561 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
2018-08-03 22:05:15,532 1 INFO ? odoo: Odoo version 11.0-20180710
2018-08-03 22:05:15,533 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2018-08-03 22:05:15,533 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/11.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
2018-08-03 22:05:15,533 1 INFO ? odoo: database: odoo@db:5432
2018-08-03 22:05:15,548 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/11.0
2018-08-03 22:05:15,548 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons
2018-08-03 22:05:15,548 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons
2018-08-03 22:05:15,961 1 INFO ? odoo.service.server: AutoReload watcher running
2018-08-03 22:05:15,964 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 130e2aeba0f6:8069
2018-08-03 22:05:16,093 1 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2018-08-03 22:24:35,737 1 INFO ? odoo.service.server: Initiating shutdown
2018-08-03 22:24:35,737 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
2018-08-03 22:25:19,469 1 INFO ? odoo: Odoo version 11.0-20180710
2018-08-03 22:25:19,469 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2018-08-03 22:25:19,469 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/11.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
2018-08-03 22:25:19,470 1 INFO ? odoo: database: odoo@dbpsql:5432
2018-08-03 22:25:19,483 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/11.0
2018-08-03 22:25:19,483 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons
2018-08-03 22:25:19,483 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons
2018-08-03 22:25:19,899 1 INFO ? odoo.service.server: AutoReload watcher running
2018-08-03 22:25:19,902 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 431e7b171e31:8069
2018-08-03 22:25:20,030 1 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2018-08-03 22:26:28,434 1 INFO ? odoo.addons.sms.wizard.send_sms: The `phonenumbers` Python module is not available. Phone number validation will be skipped. Try `pip3 install phonenumbers` to install it.
2018-08-03 22:26:28,695 1 INFO ? odoo.http: HTTP Configuring static files
2018-08-03 22:26:28,712 1 INFO ? odoo.http: Generating nondb routing
2018-08-03 22:26:28,726 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:26:28] "GET / HTTP/1.1" 200 -
2018-08-03 22:26:28,800 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:26:28] "GET /web HTTP/1.1" 303 -
2018-08-03 22:26:28,964 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:26:28] "GET /web/database/selector HTTP/1.1" 200 -
2018-08-03 22:26:34,624 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:26:34] "GET /web/database/manager HTTP/1.1" 200 -
2018-08-03 22:26:38,073 1 INFO None odoo.sql_db: ConnectionPool(used=0/count=1/max=64): Closed 1 connections to 'dbname=MILDA user=odoo password=xxxx host=dbpsql port=5432 sslmode=prefer'
2018-08-03 22:26:38,224 1 INFO None odoo.service.db: DROP DB: MILDA
2018-08-03 22:26:38,226 1 INFO None werkzeug: 172.18.0.5 - - [03/Aug/2018 22:26:38] "POST /web/database/drop HTTP/1.1" 303 -
2018-08-03 22:26:38,267 1 INFO UG odoo.modules.loading: loading 1 modules...
2018-08-03 22:26:38,291 1 INFO UG odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries
2018-08-03 22:26:38,365 1 INFO UG odoo.modules.loading: loading 79 modules...
2018-08-03 22:26:38,724 1 INFO UG odoo.modules.loading: 79 modules loaded in 0.36s, 0 queries
2018-08-03 22:26:39,746 1 INFO UG odoo.modules.loading: Modules loaded.
2018-08-03 22:26:39,757 1 INFO UG odoo.addons.base.ir.ir_http: Generating routing map
2018-08-03 22:26:39,903 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 22:26:39,905 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:26:39] "GET /web/database/manager HTTP/1.1" 200 -
2018-08-03 22:26:50,809 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:26:50] "POST /web/database/change_password HTTP/1.1" 303 -
2018-08-03 22:26:50,911 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:26:50] "GET /web/database/manager HTTP/1.1" 200 -
2018-08-03 22:26:53,520 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:26:53] "GET /web?db=UG HTTP/1.1" 303 -
2018-08-03 22:26:53,845 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:26:53] "GET /web/login HTTP/1.1" 200 -
2018-08-03 22:26:53,919 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/56/5674732e3a751a1c44c0f694cd1b222375c293e7
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e048>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/56/5674732e3a751a1c44c0f694cd1b222375c293e7'
2018-08-03 22:26:53,926 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:26:53] "GET /web/content/942-54d90ee/web.assets_frontend.0.css HTTP/1.1" 200 -
2018-08-03 22:26:53,935 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:26:53] "GET /web/binary/company_logo HTTP/1.1" 200 -
2018-08-03 22:26:53,937 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/4b/4b9b47fa72e19ab405782908040dc630f5a13f2e
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa07d208>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/4b/4b9b47fa72e19ab405782908040dc630f5a13f2e'
2018-08-03 22:26:53,940 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/2f/2f2a10828705b31748e850ec3397bf727d458b96
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa053f28>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/2f/2f2a10828705b31748e850ec3397bf727d458b96'
2018-08-03 22:26:53,941 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:26:53] "GET /web/content/943-be42584/web.assets_common.js HTTP/1.1" 200 -
2018-08-03 22:26:53,942 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:26:53] "GET /web/content/944-54d90ee/web.assets_frontend.js HTTP/1.1" 200 -
2018-08-03 22:27:02,861 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:27:02] "GET /web/login HTTP/1.1" 200 -
2018-08-03 22:27:02,953 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:27:02] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 -
2018-08-03 22:27:05,412 1 INFO UG odoo.addons.base.res.res_users: Login successful for db:UG login:milda.dvorak@gmail.com from 172.18.0.5
2018-08-03 22:27:05,473 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 22:27:05,475 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:27:05] "POST /web/login HTTP/1.1" 200 -
2018-08-03 22:27:06,145 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/af/af282536d36de83182b4a704be22a13f2e685e85
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/af/af282536d36de83182b4a704be22a13f2e685e85'
2018-08-03 22:27:06,150 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/57/576746a590a5ec2384a9428a907bc44e9117ee1e
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/57/576746a590a5ec2384a9428a907bc44e9117ee1e'
2018-08-03 22:27:06,151 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/a7/a73d3d22e9c79a282a48dcb5bea3ae31033d7c37
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/a7/a73d3d22e9c79a282a48dcb5bea3ae31033d7c37'
2018-08-03 22:27:06,152 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/c8/c8c10dbb88a65b2768cc87c9ded378fae6a0f375
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/c8/c8c10dbb88a65b2768cc87c9ded378fae6a0f375'
2018-08-03 22:27:06,152 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/45/45bff6378331e9a088a96ccbe79a7b36d72876cb
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/45/45bff6378331e9a088a96ccbe79a7b36d72876cb'
2018-08-03 22:27:06,153 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/29/29d721aeaffa7577ce7cdff7e2327b136132c450
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/29/29d721aeaffa7577ce7cdff7e2327b136132c450'
2018-08-03 22:27:06,153 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/9c/9c47efe86d2251992fa7a68a4e8a206f33e5949d
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/9c/9c47efe86d2251992fa7a68a4e8a206f33e5949d'
2018-08-03 22:27:06,154 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/bd/bd402be51199b5dbe8b8019aaa197ff08384cf31
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/bd/bd402be51199b5dbe8b8019aaa197ff08384cf31'
2018-08-03 22:27:06,154 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/43/43c6740905a73c92f02235faacdd207d9d924e62
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/43/43c6740905a73c92f02235faacdd207d9d924e62'
2018-08-03 22:27:06,155 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/17/1783fb2970f46092287402e1b59fd74ef1d23a92
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/17/1783fb2970f46092287402e1b59fd74ef1d23a92'
2018-08-03 22:27:06,155 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/f3/f3f11e52a3ead336749157f46e1c8d8a07de8b61
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/f3/f3f11e52a3ead336749157f46e1c8d8a07de8b61'
2018-08-03 22:27:06,156 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/b4/b427afd5ed82cde793e0c4b2c6901661614288f3
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/b4/b427afd5ed82cde793e0c4b2c6901661614288f3'
2018-08-03 22:27:06,156 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/cf/cf96d1aae2c821025a85d0affa1400838305fecc
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/cf/cf96d1aae2c821025a85d0affa1400838305fecc'
2018-08-03 22:27:06,157 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/92/9272fdee77faa2970921cec7bfc2c739908406c6
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/92/9272fdee77faa2970921cec7bfc2c739908406c6'
2018-08-03 22:27:06,158 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/54/549f82ae56b7397db7fcd8ca1a179494b0cfda03
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/54/549f82ae56b7397db7fcd8ca1a179494b0cfda03'
2018-08-03 22:27:06,158 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/8f/8fbaef9175ecc378e1b963bb738fc0577f414d52
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/8f/8fbaef9175ecc378e1b963bb738fc0577f414d52'
2018-08-03 22:27:06,159 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/ff/ffcd0be12fc7b54f77f4c01d7d1ec6474e1923c9
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efcaa13e198>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/ff/ffcd0be12fc7b54f77f4c01d7d1ec6474e1923c9'
2018-08-03 22:27:06,883 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 22:27:07,002 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 22:27:07,141 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:27:07] "GET /web HTTP/1.1" 200 -
2018-08-03 22:27:07,226 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/bc/bcada15fc56101024fc2b97494f55dfac672d325
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8551a58>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/bc/bcada15fc56101024fc2b97494f55dfac672d325'
2018-08-03 22:27:07,228 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:27:07] "GET /web/content/974-90fe1b2/web.assets_backend.0.css HTTP/1.1" 200 -
2018-08-03 22:27:07,248 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/c9/c983af45830626c9e4a6853a0d7e60176ac2d751
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca855d5c0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/c9/c983af45830626c9e4a6853a0d7e60176ac2d751'
2018-08-03 22:27:07,250 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/f6/f694ddbeff85a1b95da82ebeccf0162b3859c0d5
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca855d400>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/f6/f694ddbeff85a1b95da82ebeccf0162b3859c0d5'
2018-08-03 22:27:07,252 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:27:07] "GET /web/content/975-90fe1b2/web.assets_backend.1.css HTTP/1.1" 200 -
2018-08-03 22:27:07,254 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/15/15178cafb4caf1ead509e762388d1bb8c4bdc19c
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8563e80>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/15/15178cafb4caf1ead509e762388d1bb8c4bdc19c'
2018-08-03 22:27:07,254 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:27:07] "GET /web/content/976-86dc06d/web_editor.summernote.0.css HTTP/1.1" 200 -
2018-08-03 22:27:07,256 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:27:07] "GET /web/content/977-d4f9b12/web_editor.assets_editor.0.css HTTP/1.1" 200 -
2018-08-03 22:27:12,209 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:27:12] "GET /web HTTP/1.1" 200 -
2018-08-03 22:27:20,228 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:27:20] "GET /web HTTP/1.1" 200 -
2018-08-03 22:27:20,273 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Procurement: run scheduler`.
2018-08-03 22:27:20,321 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Mail: Email Queue Manager`.
2018-08-03 22:27:20,341 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Base: Auto-vacuum internal data`.
2018-08-03 22:27:20,357 1 INFO UG odoo.addons.base.ir.ir_attachment: filestore gc 0 checked, 0 removed
2018-08-03 22:27:20,472 1 INFO UG odoo.addons.base.ir.ir_autovacuum: GC'd 2 user log entries
2018-08-03 22:27:20,477 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Gamification: Goal Challenge Check`.
2018-08-03 22:27:20,540 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Calendar: Event Reminder`.
2018-08-03 22:27:20,572 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 22:27:20,577 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Mail: Fetchmail Service`.
2018-08-03 22:27:20,595 1 INFO UG odoo.addons.fetchmail.models.fetchmail: start checking for new emails on imap server web4u
2018-08-03 22:27:20,683 1 INFO UG odoo.addons.fetchmail.models.fetchmail: Fetched 0 email(s) on imap server web4u; 0 succeeded, 0 failed.
2018-08-03 22:27:22,524 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:27:22] "GET /web/login HTTP/1.1" 200 -
2018-08-03 22:27:25,134 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:27:25] "GET / HTTP/1.1" 200 -
2018-08-03 22:27:25,763 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/af/af282536d36de83182b4a704be22a13f2e685e85
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/af/af282536d36de83182b4a704be22a13f2e685e85'
2018-08-03 22:27:25,764 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/57/576746a590a5ec2384a9428a907bc44e9117ee1e
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/57/576746a590a5ec2384a9428a907bc44e9117ee1e'
2018-08-03 22:27:25,764 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/a7/a73d3d22e9c79a282a48dcb5bea3ae31033d7c37
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/a7/a73d3d22e9c79a282a48dcb5bea3ae31033d7c37'
2018-08-03 22:27:25,765 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/c8/c8c10dbb88a65b2768cc87c9ded378fae6a0f375
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/c8/c8c10dbb88a65b2768cc87c9ded378fae6a0f375'
2018-08-03 22:27:25,765 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/45/45bff6378331e9a088a96ccbe79a7b36d72876cb
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/45/45bff6378331e9a088a96ccbe79a7b36d72876cb'
2018-08-03 22:27:25,766 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/29/29d721aeaffa7577ce7cdff7e2327b136132c450
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/29/29d721aeaffa7577ce7cdff7e2327b136132c450'
2018-08-03 22:27:25,766 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/9c/9c47efe86d2251992fa7a68a4e8a206f33e5949d
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/9c/9c47efe86d2251992fa7a68a4e8a206f33e5949d'
2018-08-03 22:27:25,767 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/bd/bd402be51199b5dbe8b8019aaa197ff08384cf31
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/bd/bd402be51199b5dbe8b8019aaa197ff08384cf31'
2018-08-03 22:27:25,767 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/43/43c6740905a73c92f02235faacdd207d9d924e62
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/43/43c6740905a73c92f02235faacdd207d9d924e62'
2018-08-03 22:27:25,768 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/17/1783fb2970f46092287402e1b59fd74ef1d23a92
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/17/1783fb2970f46092287402e1b59fd74ef1d23a92'
2018-08-03 22:27:25,768 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/f3/f3f11e52a3ead336749157f46e1c8d8a07de8b61
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/f3/f3f11e52a3ead336749157f46e1c8d8a07de8b61'
2018-08-03 22:27:25,769 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/b4/b427afd5ed82cde793e0c4b2c6901661614288f3
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/b4/b427afd5ed82cde793e0c4b2c6901661614288f3'
2018-08-03 22:27:25,769 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/cf/cf96d1aae2c821025a85d0affa1400838305fecc
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/cf/cf96d1aae2c821025a85d0affa1400838305fecc'
2018-08-03 22:27:25,770 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/92/9272fdee77faa2970921cec7bfc2c739908406c6
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/92/9272fdee77faa2970921cec7bfc2c739908406c6'
2018-08-03 22:27:25,770 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/54/549f82ae56b7397db7fcd8ca1a179494b0cfda03
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/54/549f82ae56b7397db7fcd8ca1a179494b0cfda03'
2018-08-03 22:27:25,771 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/8f/8fbaef9175ecc378e1b963bb738fc0577f414d52
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/8f/8fbaef9175ecc378e1b963bb738fc0577f414d52'
2018-08-03 22:27:25,771 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/ff/ffcd0be12fc7b54f77f4c01d7d1ec6474e1923c9
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7efcd84700d0>, 1, False, ('cs_CZ',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7efca8561a20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/ff/ffcd0be12fc7b54f77f4c01d7d1ec6474e1923c9'
2018-08-03 22:27:26,414 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 22:27:26,509 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 22:27:26,631 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:27:26] "GET /web HTTP/1.1" 200 -
2018-08-03 22:27:32,116 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:27:32] "GET /web HTTP/1.1" 200 -
2018-08-03 22:27:35,953 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:27:35] "GET /web HTTP/1.1" 200 -
2018-08-03 22:29:01,002 1 INFO ? odoo.service.server: Initiating shutdown
2018-08-03 22:29:01,002 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
2018-08-03 22:29:08,589 1 INFO ? odoo: Odoo version 11.0-20180710
2018-08-03 22:29:08,590 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2018-08-03 22:29:08,590 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/11.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
2018-08-03 22:29:08,591 1 INFO ? odoo: database: odoo@dbpsql:5432
2018-08-03 22:29:08,603 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/11.0
2018-08-03 22:29:08,604 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons
2018-08-03 22:29:08,604 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons
2018-08-03 22:29:09,011 1 INFO ? odoo.service.server: AutoReload watcher running
2018-08-03 22:29:09,014 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 209ba350a5a7:8069
2018-08-03 22:29:09,142 1 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2018-08-03 22:29:22,141 1 INFO ? odoo.addons.sms.wizard.send_sms: The `phonenumbers` Python module is not available. Phone number validation will be skipped. Try `pip3 install phonenumbers` to install it.
2018-08-03 22:29:22,438 1 INFO ? odoo.http: HTTP Configuring static files
2018-08-03 22:29:22,466 1 INFO UG odoo.modules.loading: loading 1 modules...
2018-08-03 22:29:22,492 1 INFO UG odoo.modules.loading: 1 modules loaded in 0.03s, 0 queries
2018-08-03 22:29:22,573 1 INFO UG odoo.modules.loading: loading 79 modules...
2018-08-03 22:29:22,978 1 INFO UG odoo.modules.loading: 79 modules loaded in 0.40s, 0 queries
2018-08-03 22:29:24,267 1 INFO UG odoo.modules.loading: Modules loaded.
2018-08-03 22:29:24,277 1 INFO UG odoo.addons.base.ir.ir_http: Generating routing map
2018-08-03 22:29:24,365 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 22:29:24,367 1 INFO UG werkzeug: 78.108.97.26 - - [03/Aug/2018 22:29:24] "GET / HTTP/1.1" 200 -
2018-08-03 22:29:24,433 1 INFO UG werkzeug: 78.108.97.26 - - [03/Aug/2018 22:29:24] "GET /web HTTP/1.1" 303 -
2018-08-03 22:29:24,734 1 INFO UG werkzeug: 78.108.97.26 - - [03/Aug/2018 22:29:24] "GET /web/login HTTP/1.1" 200 -
2018-08-03 22:29:24,836 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/1f/1f86b714865879a4837034e11057dcf60eb8e598
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f45423508d0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/1f/1f86b714865879a4837034e11057dcf60eb8e598'
2018-08-03 22:29:24,844 1 INFO UG werkzeug: 78.108.97.26 - - [03/Aug/2018 22:29:24] "GET /web/content/941-be42584/web.assets_common.0.css HTTP/1.1" 200 -
2018-08-03 22:29:24,851 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/56/5674732e3a751a1c44c0f694cd1b222375c293e7
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f4542350c50>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/56/5674732e3a751a1c44c0f694cd1b222375c293e7'
2018-08-03 22:29:24,855 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/4b/4b9b47fa72e19ab405782908040dc630f5a13f2e
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f4542350e48>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/4b/4b9b47fa72e19ab405782908040dc630f5a13f2e'
2018-08-03 22:29:24,857 1 INFO UG werkzeug: 78.108.97.26 - - [03/Aug/2018 22:29:24] "GET /web/content/942-54d90ee/web.assets_frontend.0.css HTTP/1.1" 200 -
2018-08-03 22:29:24,858 1 INFO UG werkzeug: 78.108.97.26 - - [03/Aug/2018 22:29:24] "GET /web/content/943-be42584/web.assets_common.js HTTP/1.1" 200 -
2018-08-03 22:29:24,862 1 INFO UG werkzeug: 78.108.97.26 - - [03/Aug/2018 22:29:24] "GET /web/binary/company_logo HTTP/1.1" 200 -
2018-08-03 22:29:24,863 1 INFO UG odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/UG/2f/2f2a10828705b31748e850ec3397bf727d458b96
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f454235ffd0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 101, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/UG/2f/2f2a10828705b31748e850ec3397bf727d458b96'
2018-08-03 22:29:24,865 1 INFO UG werkzeug: 78.108.97.26 - - [03/Aug/2018 22:29:24] "GET /web/content/944-54d90ee/web.assets_frontend.js HTTP/1.1" 200 -
2018-08-03 22:29:25,018 1 INFO ? werkzeug: 78.108.97.26 - - [03/Aug/2018 22:29:25] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 -
2018-08-03 22:29:39,281 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:29:39] "GET / HTTP/1.1" 200 -
2018-08-03 22:29:39,334 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:29:39] "GET /web HTTP/1.1" 303 -
2018-08-03 22:29:39,369 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:29:39] "GET /web/login HTTP/1.1" 200 -
2018-08-03 22:29:42,718 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:29:42] "GET /web/database/manager HTTP/1.1" 200 -
2018-08-03 22:29:46,091 1 INFO None odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 5 connections to 'dbname=UG user=odoo password=xxxx host=dbpsql port=5432 sslmode=prefer'
2018-08-03 22:29:46,260 1 INFO None odoo.service.db: DROP DB: UG
2018-08-03 22:29:46,264 1 INFO None odoo.sql_db: Connection to the database failed
2018-08-03 22:29:46,271 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:29:46] "POST /web/database/drop HTTP/1.1" 500 -
2018-08-03 22:29:46,285 1 ERROR UG werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1292, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1490, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 393, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 27, in _dispatch
    return cls._set_utm(response)
  File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 19, in _set_utm
    for var, dummy, cook in request.env['utm.mixin'].tracking_fields():
  File "/usr/lib/python3/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 256, in env
    self._env = odoo.api.Environment(self.cr, self.uid, self.context)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 228, in cr
    self._cr = self.registry.cursor()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 376, in registry
    return odoo.registry(self.db)
  File "/usr/lib/python3/dist-packages/odoo/__init__.py", line 76, in registry
    return modules.registry.Registry(database_name)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 61, in __new__
    return cls.new(db_name)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 73, in new
    registry.init(db_name)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 145, in init
    with closing(self.cursor()) as cr:
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 484, in cursor
    return self._db.cursor()
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 634, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 178, in __init__
    self._cnx = pool.borrow(dsn)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 517, in _locked
    return fun(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 585, in borrow
    **connection_info)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  database "UG" does not exist
2018-08-03 22:29:54,516 1 INFO UG odoo.sql_db: Connection to the database failed
2018-08-03 22:29:54,516 1 INFO UG odoo.http: Generating nondb routing
2018-08-03 22:29:54,625 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:29:54] "GET /web/database/manager HTTP/1.1" 200 -
2018-08-03 22:31:01,347 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:31:01] "GET /web/database/manager HTTP/1.1" 200 -
2018-08-03 22:38:08,195 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:38:08] "GET /robots.txt HTTP/1.1" 404 -
2018-08-03 22:38:09,733 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:38:09] "GET / HTTP/1.1" 200 -
2018-08-03 22:38:16,938 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:38:16] "GET /web HTTP/1.1" 303 -
2018-08-03 22:38:17,424 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:38:17] "GET /web/database/selector HTTP/1.1" 200 -
2018-08-03 22:50:06,312 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:50:06] "GET /web/database/manager HTTP/1.1" 200 -
2018-08-03 22:50:31,838 1 INFO UG odoo.modules.loading: loading 1 modules...
2018-08-03 22:50:31,864 1 INFO UG odoo.modules.loading: 1 modules loaded in 0.03s, 0 queries
2018-08-03 22:50:31,943 1 INFO UG odoo.modules.loading: loading 79 modules...
2018-08-03 22:50:32,106 1 INFO UG odoo.modules.loading: 79 modules loaded in 0.16s, 0 queries
2018-08-03 22:50:32,501 1 INFO UG odoo.modules.loading: Modules loaded.
2018-08-03 22:50:32,762 1 INFO UG odoo.service.db: RESTORE DB: UG
2018-08-03 22:50:32,766 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:50:32] "POST /web/database/restore HTTP/1.1" 303 -
2018-08-03 22:50:32,832 1 INFO UG odoo.addons.base.ir.ir_http: Generating routing map
2018-08-03 22:50:33,067 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 22:50:33,072 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:50:33] "GET /web/database/manager HTTP/1.1" 200 -
2018-08-03 22:50:52,091 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:50:52] "POST /web/database/change_password HTTP/1.1" 303 -
2018-08-03 22:50:52,219 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:50:52] "GET /web/database/manager HTTP/1.1" 200 -
2018-08-03 22:50:58,456 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:50:58] "GET / HTTP/1.1" 200 -
2018-08-03 22:50:58,499 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:50:58] "GET /web HTTP/1.1" 303 -
2018-08-03 22:50:59,362 1 INFO UG odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [391]
2018-08-03 22:51:00,875 1 INFO UG odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [936]
2018-08-03 22:51:01,689 1 INFO UG odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [394]
2018-08-03 22:51:01,823 1 INFO UG odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [937]
2018-08-03 22:51:01,855 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 22:51:01,858 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:01] "GET /web/login HTTP/1.1" 200 -
2018-08-03 22:51:10,077 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Procurement: run scheduler`.
2018-08-03 22:51:10,176 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Calendar: Event Reminder`.
2018-08-03 22:51:10,213 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 22:51:10,231 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Mail: Email Queue Manager`.
2018-08-03 22:51:10,262 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Mail: Fetchmail Service`.
2018-08-03 22:51:10,279 1 INFO UG odoo.addons.fetchmail.models.fetchmail: start checking for new emails on imap server web4u
2018-08-03 22:51:10,329 1 INFO UG odoo.addons.fetchmail.models.fetchmail: Fetched 0 email(s) on imap server web4u; 0 succeeded, 0 failed.
2018-08-03 22:51:10,415 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `HR Contract: update state`.
2018-08-03 22:51:10,484 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Base: Auto-vacuum internal data`.
2018-08-03 22:51:10,538 1 INFO UG odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [934, 933]
2018-08-03 22:51:10,543 1 INFO UG odoo.addons.base.ir.ir_attachment: filestore gc 9 checked, 5 removed
2018-08-03 22:51:10,656 1 INFO UG odoo.addons.base.ir.ir_autovacuum: GC'd 0 user log entries
2018-08-03 22:51:10,661 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Gamification: Goal Challenge Check`.
2018-08-03 22:51:10,724 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Publisher: Update Notification`.
2018-08-03 22:51:32,168 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Mail: Fetchmail Service`.
2018-08-03 22:51:32,188 1 INFO UG odoo.addons.fetchmail.models.fetchmail: start checking for new emails on imap server web4u
2018-08-03 22:51:32,225 1 INFO UG odoo.addons.fetchmail.models.fetchmail: Fetched 0 email(s) on imap server web4u; 0 succeeded, 0 failed.
2018-08-03 22:51:34,446 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:34] "GET / HTTP/1.1" 200 -
2018-08-03 22:51:34,487 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:34] "GET /web HTTP/1.1" 303 -
2018-08-03 22:51:34,754 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:34] "GET /web/login HTTP/1.1" 200 -
2018-08-03 22:51:43,420 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:43] "GET / HTTP/1.1" 200 -
2018-08-03 22:51:43,510 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:43] "GET /web HTTP/1.1" 303 -
2018-08-03 22:51:43,544 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:43] "GET /web/login HTTP/1.1" 200 -
2018-08-03 22:51:43,614 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:43] "GET /web/content/941-be42584/web.assets_common.0.css HTTP/1.1" 200 -
2018-08-03 22:51:43,614 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:43] "GET /web/content/942-54d90ee/web.assets_frontend.0.css HTTP/1.1" 200 -
2018-08-03 22:51:43,631 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:43] "GET /web/content/944-54d90ee/web.assets_frontend.js HTTP/1.1" 200 -
2018-08-03 22:51:43,633 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:43] "GET /web/binary/company_logo HTTP/1.1" 200 -
2018-08-03 22:51:43,642 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:43] "GET /web/content/943-be42584/web.assets_common.js HTTP/1.1" 200 -
2018-08-03 22:51:44,453 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:44] "GET /web/webclient/qweb?mods= HTTP/1.1" 200 -
2018-08-03 22:51:44,464 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:44] "POST /web/webclient/bootstrap_translations HTTP/1.1" 200 -
2018-08-03 22:51:44,549 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:44] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 -
2018-08-03 22:51:57,512 1 INFO UG odoo.addons.base.res.res_users: Login successful for db:UG login:milda.dvorak@gmail.com from 172.18.0.5
2018-08-03 22:51:57,536 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 22:51:57,539 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:51:57] "POST /web/login HTTP/1.1" 200 -
2018-08-03 22:51:58,963 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 22:52:01,104 1 INFO UG odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [939, 938]
2018-08-03 22:52:01,482 1 INFO UG odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [242]
2018-08-03 22:52:02,061 1 INFO UG odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [243]
2018-08-03 22:52:02,502 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 22:52:03,110 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 22:52:03,195 1 INFO UG odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [940]
2018-08-03 22:52:03,397 1 INFO UG odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [246]
2018-08-03 22:52:03,575 1 INFO UG odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [247]
2018-08-03 22:52:03,723 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 22:52:03,726 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:03] "GET /web HTTP/1.1" 200 -
2018-08-03 22:52:03,828 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:03] "GET /web/content/945-90fe1b2/web.assets_backend.0.css HTTP/1.1" 200 -
2018-08-03 22:52:03,870 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:03] "GET /web/content/948-d4f9b12/web_editor.assets_editor.0.css HTTP/1.1" 200 -
2018-08-03 22:52:03,876 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:03] "GET /web/content/946-90fe1b2/web.assets_backend.1.css HTTP/1.1" 200 -
2018-08-03 22:52:03,881 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:03] "GET /web/content/947-86dc06d/web_editor.summernote.0.css HTTP/1.1" 200 -
2018-08-03 22:52:03,892 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:03] "GET /web/content/950-86dc06d/web_editor.summernote.js HTTP/1.1" 200 -
2018-08-03 22:52:03,903 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:03] "GET /web/content/949-90fe1b2/web.assets_backend.js HTTP/1.1" 200 -
2018-08-03 22:52:03,954 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:03] "GET /web/content/951-d4f9b12/web_editor.assets_editor.js HTTP/1.1" 200 -
2018-08-03 22:52:05,496 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:05] "GET /web/webclient/qweb?mods=web,base,bus,web_tour,mail,sales_team,calendar,web_planner,contacts,crm,product,portal,project,barcodes,stock,account,sale,account_invoicing,sale_management,hr,hr_timesheet,hr_holidays,account_accountant_cbc,hr_payroll,purchase,hr_attendance,hr_expense,account_bank_statement_import,auth_signup,base_import,document,web_kanban_gauge,gamification,hr_gamification,hr_org_chart,iap,payment,payment_transfer,sale_stock,sale_timesheet,sms,web_diagram,web_editor,web_settings_dashboard HTTP/1.1" 200 -
2018-08-03 22:52:05,611 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:05] "POST /web/dataset/call HTTP/1.1" 200 -
2018-08-03 22:52:05,745 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:05] "POST /web/webclient/translations HTTP/1.1" 200 -
2018-08-03 22:52:05,765 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:05] "GET /web/webclient/locale/cs_CZ HTTP/1.1" 200 -
2018-08-03 22:52:05,835 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:05] "GET /web/static/lib/fontawesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 -
2018-08-03 22:52:05,868 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:05] "POST /web/dataset/call_kw/res.users/activity_user_count HTTP/1.1" 200 -
2018-08-03 22:52:05,885 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:05] "POST /mail/client_action HTTP/1.1" 200 -
2018-08-03 22:52:05,886 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:05] "POST /web/dataset/call_kw/res.users/read HTTP/1.1" 200 -
2018-08-03 22:52:05,900 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:05] "POST /calendar/notify HTTP/1.1" 200 -
2018-08-03 22:52:05,914 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:05] "GET /project/static/description/icon.png HTTP/1.1" 200 -
2018-08-03 22:52:05,919 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:05] "GET /web/binary/company_logo?db=UG&company=1 HTTP/1.1" 200 -
2018-08-03 22:52:05,942 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:05] "GET /web/image?model=res.users&field=image_small&id=1 HTTP/1.1" 200 -
2018-08-03 22:52:05,963 1 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2018-08-03 22:52:05,984 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:05] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 22:52:06,135 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:06] "POST /web/dataset/call_kw/mail.message/load_views HTTP/1.1" 200 -
2018-08-03 22:52:06,201 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:06] "POST /web/dataset/call_kw/web.planner/search_read HTTP/1.1" 200 -
2018-08-03 22:52:06,237 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:06] "POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.1" 200 -
2018-08-03 22:52:06,310 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:06] "POST /web/dataset/call_kw/mail.message/message_fetch HTTP/1.1" 200 -
2018-08-03 22:52:46,142 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:46] "POST /web/dataset/call_kw/mail.message/message_fetch HTTP/1.1" 200 -
2018-08-03 22:52:46,562 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:46] "GET /web/image/res.partner/14/image_small HTTP/1.1" 200 -
2018-08-03 22:52:46,583 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:46] "GET /web/image/res.partner/3/image_small HTTP/1.1" 200 -
2018-08-03 22:52:46,589 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:46] "GET /web/image/res.partner/16/image_small HTTP/1.1" 200 -
2018-08-03 22:52:54,263 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:54] "POST /web/dataset/call_kw/mail.message/message_fetch HTTP/1.1" 200 -
2018-08-03 22:52:54,312 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:54] "POST /web/dataset/call_kw/mail.channel/channel_fetch_listeners HTTP/1.1" 200 -
2018-08-03 22:52:55,968 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:55] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 22:52:58,196 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:58] "POST /web/dataset/call_kw/mail.message/message_fetch HTTP/1.1" 200 -
2018-08-03 22:52:58,248 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:52:58] "POST /web/dataset/call_kw/mail.channel/channel_fetch_listeners HTTP/1.1" 200 -
2018-08-03 22:53:46,006 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:53:46] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 22:54:36,042 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:54:36] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 22:55:26,076 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:55:26] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 22:56:16,113 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:56:16] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 22:56:37,512 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Mail: Fetchmail Service`.
2018-08-03 22:56:37,530 1 INFO UG odoo.addons.fetchmail.models.fetchmail: start checking for new emails on imap server web4u
2018-08-03 22:56:37,596 1 INFO UG odoo.addons.fetchmail.models.fetchmail: Fetched 0 email(s) on imap server web4u; 0 succeeded, 0 failed.
2018-08-03 22:57:06,149 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:57:06] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 22:57:56,186 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:57:56] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 22:58:46,225 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:58:46] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 22:58:54,144 1 INFO ? odoo.service.server: Initiating shutdown
2018-08-03 22:58:54,144 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
2018-08-03 22:58:58,647 1 INFO ? odoo: Odoo version 11.0-20180710
2018-08-03 22:58:58,648 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2018-08-03 22:58:58,648 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/11.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
2018-08-03 22:58:58,648 1 INFO ? odoo: database: odoo@dbpsql:5432
2018-08-03 22:58:58,661 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/11.0
2018-08-03 22:58:58,662 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons
2018-08-03 22:58:58,662 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons
2018-08-03 22:58:59,072 1 INFO ? odoo.service.server: AutoReload watcher running
2018-08-03 22:58:59,076 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on ug.dravom.com.ug.dravom.com:8069
2018-08-03 22:58:59,206 1 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2018-08-03 22:59:05,569 1 INFO ? odoo.addons.sms.wizard.send_sms: The `phonenumbers` Python module is not available. Phone number validation will be skipped. Try `pip3 install phonenumbers` to install it.
2018-08-03 22:59:05,861 1 INFO ? odoo.http: HTTP Configuring static files
2018-08-03 22:59:05,882 1 INFO UG odoo.modules.loading: loading 1 modules...
2018-08-03 22:59:05,909 1 INFO UG odoo.modules.loading: 1 modules loaded in 0.03s, 0 queries
2018-08-03 22:59:05,988 1 INFO UG odoo.modules.loading: loading 79 modules...
2018-08-03 22:59:06,387 1 INFO UG odoo.modules.loading: 79 modules loaded in 0.40s, 0 queries
2018-08-03 22:59:07,638 1 INFO UG odoo.modules.loading: Modules loaded.
2018-08-03 22:59:07,649 1 INFO UG odoo.addons.base.ir.ir_http: Generating routing map
2018-08-03 22:59:09,267 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 22:59:09,401 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 22:59:09,647 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 22:59:09,656 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:09] "GET /web HTTP/1.1" 200 -
2018-08-03 22:59:09,663 1 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2018-08-03 22:59:10,163 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:10] "GET /web/webclient/qweb?mods=web,base,bus,web_tour,mail,sales_team,calendar,web_planner,contacts,crm,product,portal,project,barcodes,stock,account,sale,account_invoicing,sale_management,hr,hr_timesheet,hr_holidays,account_accountant_cbc,hr_payroll,purchase,hr_attendance,hr_expense,account_bank_statement_import,auth_signup,base_import,document,web_kanban_gauge,gamification,hr_gamification,hr_org_chart,iap,payment,payment_transfer,sale_stock,sale_timesheet,sms,web_diagram,web_editor,web_settings_dashboard HTTP/1.1" 304 -
2018-08-03 22:59:10,353 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:10] "POST /web/dataset/call HTTP/1.1" 200 -
2018-08-03 22:59:10,502 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:10] "POST /web/webclient/translations HTTP/1.1" 200 -
2018-08-03 22:59:10,503 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:10] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 -
2018-08-03 22:59:10,602 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:10] "POST /web/dataset/call_kw/res.users/activity_user_count HTTP/1.1" 200 -
2018-08-03 22:59:10,627 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:10] "POST /mail/client_action HTTP/1.1" 200 -
2018-08-03 22:59:10,655 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:10] "POST /calendar/notify HTTP/1.1" 200 -
2018-08-03 22:59:10,655 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:10] "GET /web/image?model=res.users&field=image_small&id=1 HTTP/1.1" 304 -
2018-08-03 22:59:10,694 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:10] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 22:59:10,851 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:10] "POST /web/dataset/call_kw/mail.message/load_views HTTP/1.1" 200 -
2018-08-03 22:59:10,922 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:10] "POST /web/dataset/call_kw/web.planner/search_read HTTP/1.1" 200 -
2018-08-03 22:59:10,959 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:10] "POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.1" 200 -
2018-08-03 22:59:11,058 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:11] "POST /web/dataset/call_kw/mail.message/message_fetch HTTP/1.1" 200 -
2018-08-03 22:59:11,799 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:11] "GET /web/image/res.partner/3/image_small HTTP/1.1" 304 -
2018-08-03 22:59:11,806 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:11] "GET /web/image/res.partner/16/image_small HTTP/1.1" 304 -
2018-08-03 22:59:11,807 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:11] "GET /web/image/res.partner/14/image_small HTTP/1.1" 304 -
2018-08-03 22:59:18,651 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:18] "GET / HTTP/1.1" 200 -
2018-08-03 22:59:18,814 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:18] "GET /web HTTP/1.1" 303 -
2018-08-03 22:59:18,964 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:18] "GET /web/login HTTP/1.1" 200 -
2018-08-03 22:59:19,033 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:19] "GET /web/content/941-be42584/web.assets_common.0.css HTTP/1.1" 200 -
2018-08-03 22:59:19,060 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:19] "GET /web/content/942-54d90ee/web.assets_frontend.0.css HTTP/1.1" 200 -
2018-08-03 22:59:19,069 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:19] "GET /web/binary/company_logo HTTP/1.1" 200 -
2018-08-03 22:59:19,077 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:19] "GET /web/content/943-be42584/web.assets_common.js HTTP/1.1" 200 -
2018-08-03 22:59:19,082 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:19] "GET /web/content/944-54d90ee/web.assets_frontend.js HTTP/1.1" 200 -
2018-08-03 22:59:19,893 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:19] "GET /web/webclient/qweb?mods= HTTP/1.1" 200 -
2018-08-03 22:59:19,894 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:19] "POST /web/webclient/bootstrap_translations HTTP/1.1" 200 -
2018-08-03 22:59:27,152 1 INFO UG odoo.addons.base.res.res_users: Login successful for db:UG login:milda.dvorak@gmail.com from 172.18.0.5
2018-08-03 22:59:27,178 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 22:59:27,180 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:27] "POST /web/login HTTP/1.1" 200 -
2018-08-03 22:59:28,713 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 22:59:28,939 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 22:59:29,099 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:29] "GET /web HTTP/1.1" 200 -
2018-08-03 22:59:29,226 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:29] "GET /web/content/945-90fe1b2/web.assets_backend.0.css HTTP/1.1" 200 -
2018-08-03 22:59:29,253 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:29] "GET /web/content/946-90fe1b2/web.assets_backend.1.css HTTP/1.1" 200 -
2018-08-03 22:59:29,255 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:29] "GET /web/content/947-86dc06d/web_editor.summernote.0.css HTTP/1.1" 200 -
2018-08-03 22:59:29,256 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:29] "GET /web/content/948-d4f9b12/web_editor.assets_editor.0.css HTTP/1.1" 200 -
2018-08-03 22:59:29,285 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:29] "GET /web/content/950-86dc06d/web_editor.summernote.js HTTP/1.1" 200 -
2018-08-03 22:59:29,287 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:29] "GET /web/content/949-90fe1b2/web.assets_backend.js HTTP/1.1" 200 -
2018-08-03 22:59:29,308 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:29] "GET /web/content/951-d4f9b12/web_editor.assets_editor.js HTTP/1.1" 200 -
2018-08-03 22:59:30,418 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:30] "GET /web/webclient/qweb?mods=web,base,bus,web_tour,mail,sales_team,calendar,web_planner,contacts,crm,product,portal,project,barcodes,stock,account,sale,account_invoicing,sale_management,hr,hr_timesheet,hr_holidays,account_accountant_cbc,hr_payroll,purchase,hr_attendance,hr_expense,account_bank_statement_import,auth_signup,base_import,document,web_kanban_gauge,gamification,hr_gamification,hr_org_chart,iap,payment,payment_transfer,sale_stock,sale_timesheet,sms,web_diagram,web_editor,web_settings_dashboard HTTP/1.1" 200 -
2018-08-03 22:59:30,563 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:30] "POST /web/dataset/call HTTP/1.1" 200 -
2018-08-03 22:59:30,654 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:30] "POST /web/webclient/translations HTTP/1.1" 200 -
2018-08-03 22:59:30,676 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:30] "GET /web/webclient/locale/cs_CZ HTTP/1.1" 200 -
2018-08-03 22:59:30,773 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:30] "POST /mail/client_action HTTP/1.1" 200 -
2018-08-03 22:59:30,836 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:30] "POST /web/dataset/call_kw/res.users/activity_user_count HTTP/1.1" 200 -
2018-08-03 22:59:30,845 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:30] "GET /web/static/lib/fontawesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 -
2018-08-03 22:59:30,917 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:30] "POST /web/dataset/call_kw/res.users/read HTTP/1.1" 200 -
2018-08-03 22:59:30,958 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:30] "GET /project/static/description/icon.png HTTP/1.1" 200 -
2018-08-03 22:59:30,959 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:30] "POST /calendar/notify HTTP/1.1" 200 -
2018-08-03 22:59:30,967 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:30] "GET /web/binary/company_logo?db=UG&company=1 HTTP/1.1" 200 -
2018-08-03 22:59:30,983 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:30] "GET /web/image?model=res.users&field=image_small&id=1 HTTP/1.1" 200 -
2018-08-03 22:59:31,009 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:31] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 22:59:31,148 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:31] "POST /web/dataset/call_kw/mail.message/load_views HTTP/1.1" 200 -
2018-08-03 22:59:31,211 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:31] "POST /web/dataset/call_kw/web.planner/search_read HTTP/1.1" 200 -
2018-08-03 22:59:31,318 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:31] "POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.1" 200 -
2018-08-03 22:59:31,465 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:31] "POST /web/dataset/call_kw/mail.message/message_fetch HTTP/1.1" 200 -
2018-08-03 22:59:59,668 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 22:59:59] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:00:00,702 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:00:00] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:00:20,988 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:00:20] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:00:50,747 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:00:50] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:01:11,027 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:01:11] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:01:40,784 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:01:40] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:01:59,515 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Mail: Fetchmail Service`.
2018-08-03 23:01:59,533 1 INFO UG odoo.addons.fetchmail.models.fetchmail: start checking for new emails on imap server web4u
2018-08-03 23:01:59,591 1 INFO UG odoo.addons.fetchmail.models.fetchmail: Fetched 0 email(s) on imap server web4u; 0 succeeded, 0 failed.
2018-08-03 23:02:01,063 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:02:01] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:02:30,825 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:02:30] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:02:51,097 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:02:51] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:03:20,870 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:03:20] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:03:41,136 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:03:41] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:04:10,907 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:04:10] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:04:31,173 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:04:31] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:05:00,943 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:05:00] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:05:21,212 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:05:21] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:05:50,977 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:05:50] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:06:11,249 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:06:11] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:06:41,014 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:06:41] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:06:49,975 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:06:49] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:06:50,363 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:06:50] "POST /web/dataset/call_kw/res.users/load_views HTTP/1.1" 200 -
2018-08-03 23:06:50,503 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:06:50] "POST /web/dataset/call_kw/res.users/read HTTP/1.1" 200 -
2018-08-03 23:06:50,955 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 23:06:50] "GET /web/static/src/xml/dialog.xml HTTP/1.1" 200 -
2018-08-03 23:06:50,960 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 23:06:50] "GET /web/static/src/img/placeholder.png HTTP/1.1" 200 -
2018-08-03 23:06:55,951 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:06:55] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:06:56,006 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:06:56] "POST /web_settings_dashboard/data HTTP/1.1" 200 -
2018-08-03 23:06:56,030 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:06:56] "POST /web/dataset/call_kw HTTP/1.1" 200 -
2018-08-03 23:06:56,058 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:06:56] "POST /web/dataset/call_kw/web.planner/search_read HTTP/1.1" 200 -
2018-08-03 23:06:59,802 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Mail: Fetchmail Service`.
2018-08-03 23:06:59,837 1 INFO UG odoo.addons.fetchmail.models.fetchmail: start checking for new emails on imap server web4u
2018-08-03 23:06:59,897 1 INFO UG odoo.addons.fetchmail.models.fetchmail: Fetched 0 email(s) on imap server web4u; 0 succeeded, 0 failed.
2018-08-03 23:07:00,296 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 23:07:00,385 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 23:07:00,477 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:00] "GET /web?debug HTTP/1.1" 200 -
2018-08-03 23:07:01,048 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "GET /web/webclient/qweb?mods=web,base,bus,web_tour,mail,sales_team,calendar,web_planner,contacts,crm,product,portal,project,barcodes,stock,account,sale,account_invoicing,sale_management,hr,hr_timesheet,hr_holidays,account_accountant_cbc,hr_payroll,purchase,hr_attendance,hr_expense,account_bank_statement_import,auth_signup,base_import,document,web_kanban_gauge,gamification,hr_gamification,hr_org_chart,iap,payment,payment_transfer,sale_stock,sale_timesheet,sms,web_diagram,web_editor,web_settings_dashboard HTTP/1.1" 304 -
2018-08-03 23:07:01,160 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /web/dataset/call HTTP/1.1" 200 -
2018-08-03 23:07:01,251 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /web/webclient/translations HTTP/1.1" 200 -
2018-08-03 23:07:01,286 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:07:01,338 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /mail/client_action HTTP/1.1" 200 -
2018-08-03 23:07:01,343 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /web/dataset/call_kw/res.users/check_access_rights HTTP/1.1" 200 -
2018-08-03 23:07:01,354 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /web/dataset/call_kw/res.users/has_group HTTP/1.1" 200 -
2018-08-03 23:07:01,365 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /web/dataset/call_kw/ir.model.data/xmlid_to_res_id HTTP/1.1" 200 -
2018-08-03 23:07:01,367 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /web/dataset/call_kw/ir.ui.view/check_access_rights HTTP/1.1" 200 -
2018-08-03 23:07:01,384 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /web/dataset/call_kw/res.users/activity_user_count HTTP/1.1" 200 -
2018-08-03 23:07:01,400 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /web/dataset/call_kw/res.users/read HTTP/1.1" 200 -
2018-08-03 23:07:01,407 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /calendar/notify HTTP/1.1" 200 -
2018-08-03 23:07:01,415 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "GET /web/image?model=res.users&field=image_small&id=1 HTTP/1.1" 304 -
2018-08-03 23:07:01,536 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:07:01,609 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /web/dataset/call_kw/mail.message/load_views HTTP/1.1" 200 -
2018-08-03 23:07:01,628 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /web/dataset/call_kw/web.planner/search_read HTTP/1.1" 200 -
2018-08-03 23:07:01,769 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.1" 200 -
2018-08-03 23:07:01,855 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:01] "POST /web/dataset/call_kw/mail.message/message_fetch HTTP/1.1" 200 -
2018-08-03 23:07:31,050 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:31] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:07:51,319 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:51] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:07:51,453 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:07:51] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:08:41,353 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:41] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:08:41,490 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:41] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:08:45,451 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:45] "GET / HTTP/1.1" 200 -
2018-08-03 23:08:45,858 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:45] "GET /web HTTP/1.1" 303 -
2018-08-03 23:08:46,002 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:46] "GET /web/login HTTP/1.1" 200 -
2018-08-03 23:08:56,373 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:56] "GET / HTTP/1.1" 200 -
2018-08-03 23:08:56,591 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:56] "GET /web HTTP/1.1" 200 -
2018-08-03 23:08:57,071 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:57] "GET /web/webclient/qweb?mods=web,base,bus,web_tour,mail,sales_team,calendar,web_planner,contacts,crm,product,portal,project,barcodes,stock,account,sale,account_invoicing,sale_management,hr,hr_timesheet,hr_holidays,account_accountant_cbc,hr_payroll,purchase,hr_attendance,hr_expense,account_bank_statement_import,auth_signup,base_import,document,web_kanban_gauge,gamification,hr_gamification,hr_org_chart,iap,payment,payment_transfer,sale_stock,sale_timesheet,sms,web_diagram,web_editor,web_settings_dashboard HTTP/1.1" 304 -
2018-08-03 23:08:57,202 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:57] "POST /web/dataset/call HTTP/1.1" 200 -
2018-08-03 23:08:57,327 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:57] "POST /web/webclient/translations HTTP/1.1" 200 -
2018-08-03 23:08:57,406 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:57] "POST /mail/client_action HTTP/1.1" 200 -
2018-08-03 23:08:57,423 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:57] "POST /web/dataset/call_kw/res.users/activity_user_count HTTP/1.1" 200 -
2018-08-03 23:08:57,435 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:57] "POST /web/dataset/call_kw/res.users/read HTTP/1.1" 200 -
2018-08-03 23:08:57,440 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:57] "POST /calendar/notify HTTP/1.1" 200 -
2018-08-03 23:08:57,449 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:57] "GET /web/image?model=res.users&field=image_small&id=1 HTTP/1.1" 304 -
2018-08-03 23:08:57,499 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:57] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:08:57,579 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:57] "POST /web/dataset/call_kw/mail.message/load_views HTTP/1.1" 200 -
2018-08-03 23:08:57,661 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:57] "POST /web/dataset/call_kw/web.planner/search_read HTTP/1.1" 200 -
2018-08-03 23:08:57,680 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:57] "POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.1" 200 -
2018-08-03 23:08:57,801 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:08:57] "POST /web/dataset/call_kw/mail.message/message_fetch HTTP/1.1" 200 -
2018-08-03 23:09:06,152 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:09:06] "GET / HTTP/1.1" 200 -
2018-08-03 23:09:06,384 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:09:06] "GET /web HTTP/1.1" 303 -
2018-08-03 23:09:06,416 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:09:06] "GET /web/login HTTP/1.1" 200 -
2018-08-03 23:09:31,382 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:09:31] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:09:47,475 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:09:47] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:10:21,420 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:10:21] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:10:37,517 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:10:37] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:11:11,455 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:11:11] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:11:11,911 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Calendar: Event Reminder`.
2018-08-03 23:11:11,944 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 23:11:27,552 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:11:27] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:12:00,223 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Mail: Fetchmail Service`.
2018-08-03 23:12:00,244 1 INFO UG odoo.addons.fetchmail.models.fetchmail: start checking for new emails on imap server web4u
2018-08-03 23:12:00,285 1 INFO UG odoo.addons.fetchmail.models.fetchmail: Fetched 0 email(s) on imap server web4u; 0 succeeded, 0 failed.
2018-08-03 23:12:01,491 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:01] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:12:13,689 1 INFO ? odoo.service.server: Initiating shutdown
2018-08-03 23:12:13,689 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
2018-08-03 23:12:18,711 1 INFO ? odoo: Odoo version 11.0-20180710
2018-08-03 23:12:18,712 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2018-08-03 23:12:18,712 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/11.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
2018-08-03 23:12:18,712 1 INFO ? odoo: database: odoo@dbpsql:5432
2018-08-03 23:12:18,725 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/11.0
2018-08-03 23:12:18,726 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons
2018-08-03 23:12:18,726 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons
2018-08-03 23:12:19,143 1 INFO ? odoo.service.server: AutoReload watcher running
2018-08-03 23:12:19,147 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on ug.dravom.com.dravom.com:8069
2018-08-03 23:12:19,276 1 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2018-08-03 23:12:30,197 1 INFO ? odoo.addons.sms.wizard.send_sms: The `phonenumbers` Python module is not available. Phone number validation will be skipped. Try `pip3 install phonenumbers` to install it.
2018-08-03 23:12:30,494 1 INFO ? odoo.http: HTTP Configuring static files
2018-08-03 23:12:30,515 1 INFO UG odoo.modules.loading: loading 1 modules...
2018-08-03 23:12:30,542 1 INFO UG odoo.modules.loading: 1 modules loaded in 0.03s, 0 queries
2018-08-03 23:12:30,622 1 INFO UG odoo.modules.loading: loading 79 modules...
2018-08-03 23:12:31,023 1 INFO UG odoo.modules.loading: 79 modules loaded in 0.40s, 0 queries
2018-08-03 23:12:32,274 1 INFO UG odoo.modules.loading: Modules loaded.
2018-08-03 23:12:32,285 1 INFO UG odoo.addons.base.ir.ir_http: Generating routing map
2018-08-03 23:12:32,396 1 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2018-08-03 23:12:38,516 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 23:12:38,518 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:38] "GET / HTTP/1.1" 200 -
2018-08-03 23:12:38,560 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:38] "GET /web HTTP/1.1" 303 -
2018-08-03 23:12:38,856 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:38] "GET /web/login HTTP/1.1" 200 -
2018-08-03 23:12:38,891 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:38] "GET /web/content/941-be42584/web.assets_common.0.css HTTP/1.1" 200 -
2018-08-03 23:12:38,911 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:38] "GET /web/content/942-54d90ee/web.assets_frontend.0.css HTTP/1.1" 200 -
2018-08-03 23:12:38,921 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:38] "GET /web/binary/company_logo HTTP/1.1" 200 -
2018-08-03 23:12:38,932 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:38] "GET /web/content/944-54d90ee/web.assets_frontend.js HTTP/1.1" 200 -
2018-08-03 23:12:38,940 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:38] "GET /web/content/943-be42584/web.assets_common.js HTTP/1.1" 200 -
2018-08-03 23:12:39,697 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:39] "GET /web/webclient/qweb?mods= HTTP/1.1" 200 -
2018-08-03 23:12:39,702 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:39] "POST /web/webclient/bootstrap_translations HTTP/1.1" 200 -
2018-08-03 23:12:43,840 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:43] "GET / HTTP/1.1" 200 -
2018-08-03 23:12:45,616 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 23:12:45,728 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 23:12:45,872 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:45] "GET /web HTTP/1.1" 200 -
2018-08-03 23:12:46,356 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:46] "GET /web/webclient/qweb?mods=web,base,bus,web_tour,mail,sales_team,calendar,web_planner,contacts,crm,product,portal,project,barcodes,stock,account,sale,account_invoicing,sale_management,hr,hr_timesheet,hr_holidays,account_accountant_cbc,hr_payroll,purchase,hr_attendance,hr_expense,account_bank_statement_import,auth_signup,base_import,document,web_kanban_gauge,gamification,hr_gamification,hr_org_chart,iap,payment,payment_transfer,sale_stock,sale_timesheet,sms,web_diagram,web_editor,web_settings_dashboard HTTP/1.1" 304 -
2018-08-03 23:12:46,481 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:46] "POST /web/dataset/call HTTP/1.1" 200 -
2018-08-03 23:12:46,562 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:46] "POST /web/webclient/translations HTTP/1.1" 200 -
2018-08-03 23:12:46,667 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:46] "POST /mail/client_action HTTP/1.1" 200 -
2018-08-03 23:12:46,691 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:46] "POST /web/dataset/call_kw/res.users/read HTTP/1.1" 200 -
2018-08-03 23:12:46,700 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:46] "POST /web/dataset/call_kw/res.users/activity_user_count HTTP/1.1" 200 -
2018-08-03 23:12:46,703 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:46] "POST /calendar/notify HTTP/1.1" 200 -
2018-08-03 23:12:46,721 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:46] "GET /web/image?model=res.users&field=image_small&id=1 HTTP/1.1" 304 -
2018-08-03 23:12:46,761 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:46] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:12:46,889 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:46] "POST /web/dataset/call_kw/mail.message/load_views HTTP/1.1" 200 -
2018-08-03 23:12:46,968 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:46] "POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.1" 200 -
2018-08-03 23:12:47,013 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:47] "POST /web/dataset/call_kw/web.planner/search_read HTTP/1.1" 200 -
2018-08-03 23:12:47,022 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:12:47] "POST /web/dataset/call_kw/mail.message/message_fetch HTTP/1.1" 200 -
2018-08-03 23:13:22,401 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:22] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:13:36,774 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:36] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:13:53,125 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:53] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:13:53,165 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:53] "POST /web_settings_dashboard/data HTTP/1.1" 200 -
2018-08-03 23:13:53,182 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:53] "POST /web/dataset/call_kw HTTP/1.1" 200 -
2018-08-03 23:13:53,223 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:53] "POST /web/dataset/call_kw/web.planner/search_read HTTP/1.1" 200 -
2018-08-03 23:13:57,122 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 23:13:57,208 1 WARNING UG odoo.modules.module: module account_accountant: module not found
2018-08-03 23:13:57,300 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:57] "GET /web?debug HTTP/1.1" 200 -
2018-08-03 23:13:57,605 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:57] "GET /web/webclient/qweb?mods=web,base,bus,web_tour,mail,sales_team,calendar,web_planner,contacts,crm,product,portal,project,barcodes,stock,account,sale,account_invoicing,sale_management,hr,hr_timesheet,hr_holidays,account_accountant_cbc,hr_payroll,purchase,hr_attendance,hr_expense,account_bank_statement_import,auth_signup,base_import,document,web_kanban_gauge,gamification,hr_gamification,hr_org_chart,iap,payment,payment_transfer,sale_stock,sale_timesheet,sms,web_diagram,web_editor,web_settings_dashboard HTTP/1.1" 304 -
2018-08-03 23:13:57,672 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:57] "POST /web/dataset/call HTTP/1.1" 200 -
2018-08-03 23:13:57,833 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:57] "POST /web/webclient/translations HTTP/1.1" 200 -
2018-08-03 23:13:57,925 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:57] "POST /mail/client_action HTTP/1.1" 200 -
2018-08-03 23:13:57,946 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:57] "POST /web/dataset/call_kw/res.users/check_access_rights HTTP/1.1" 200 -
2018-08-03 23:13:57,949 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:57] "GET /web/image?model=res.users&field=image_small&id=1 HTTP/1.1" 304 -
2018-08-03 23:13:57,959 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:57] "POST /web/dataset/call_kw/res.users/has_group HTTP/1.1" 200 -
2018-08-03 23:13:57,959 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:57] "POST /web/dataset/call_kw/ir.model.data/xmlid_to_res_id HTTP/1.1" 200 -
2018-08-03 23:13:57,963 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:57] "POST /web/dataset/call_kw/ir.ui.view/check_access_rights HTTP/1.1" 200 -
2018-08-03 23:13:57,979 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:57] "POST /web/dataset/call_kw/res.users/read HTTP/1.1" 200 -
2018-08-03 23:13:57,982 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:57] "POST /web/dataset/call_kw/res.users/activity_user_count HTTP/1.1" 200 -
2018-08-03 23:13:57,994 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:57] "POST /calendar/notify HTTP/1.1" 200 -
2018-08-03 23:13:58,033 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:58] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:13:58,101 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:58] "POST /web/dataset/call_kw/mail.message/load_views HTTP/1.1" 200 -
2018-08-03 23:13:58,157 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:58] "POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.1" 200 -
2018-08-03 23:13:58,217 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:58] "POST /web/dataset/call_kw/web.planner/search_read HTTP/1.1" 200 -
2018-08-03 23:13:58,227 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:13:58] "POST /web/dataset/call_kw/mail.message/message_fetch HTTP/1.1" 200 -
2018-08-03 23:14:02,655 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:14:02] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:14:02,705 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:14:02] "POST /web_settings_dashboard/data HTTP/1.1" 200 -
2018-08-03 23:14:02,720 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:14:02] "POST /web/dataset/call_kw HTTP/1.1" 200 -
2018-08-03 23:14:02,759 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:14:02] "POST /web/dataset/call_kw/web.planner/search_read HTTP/1.1" 200 -
2018-08-03 23:14:12,441 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:14:12] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:14:48,012 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:14:48] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:15:27,791 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:27] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:15:27,955 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:27] "POST /web/dataset/call_kw/fetchmail.server/load_views HTTP/1.1" 200 -
2018-08-03 23:15:28,051 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:28] "POST /web/dataset/search_read HTTP/1.1" 200 -
2018-08-03 23:15:30,053 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:30] "POST /web/dataset/call_kw/fetchmail.server/read HTTP/1.1" 200 -
2018-08-03 23:15:30,160 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:30] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:15:30,175 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:30] "GET /web/static/src/img/form_sheetbg.png HTTP/1.1" 200 -
2018-08-03 23:15:33,200 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:33] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:15:36,829 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:36] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:15:36,850 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:36] "POST /web/dataset/call_button HTTP/1.1" 200 -
2018-08-03 23:15:36,873 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:36] "POST /web/dataset/call_kw/fetchmail.server/read HTTP/1.1" 200 -
2018-08-03 23:15:36,989 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:36] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:15:38,056 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:38] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:15:47,434 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:47] "POST /web/dataset/call_kw/fetchmail.server/write HTTP/1.1" 200 -
2018-08-03 23:15:47,453 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:47] "POST /web/dataset/call_kw/fetchmail.server/read HTTP/1.1" 200 -
2018-08-03 23:15:47,477 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:47] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:15:47,527 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:47] "POST /web/dataset/call_button HTTP/1.1" 200 -
2018-08-03 23:15:47,548 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:47] "POST /web/dataset/call_kw/fetchmail.server/read HTTP/1.1" 200 -
2018-08-03 23:15:47,661 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:47] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:15:55,165 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:55] "POST /web/dataset/search_read HTTP/1.1" 200 -
2018-08-03 23:15:57,053 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:57] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:15:57,108 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:57] "POST /web/dataset/call_kw/ir.mail_server/load_views HTTP/1.1" 200 -
2018-08-03 23:15:57,150 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:57] "POST /web/dataset/search_read HTTP/1.1" 200 -
2018-08-03 23:15:59,084 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:59] "POST /web/dataset/call_kw/ir.mail_server/read HTTP/1.1" 200 -
2018-08-03 23:15:59,141 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:15:59] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:16:00,835 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:00] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:16:07,309 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:07] "POST /web/dataset/call_kw/ir.mail_server/write HTTP/1.1" 200 -
2018-08-03 23:16:07,332 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:07] "POST /web/dataset/call_kw/ir.mail_server/read HTTP/1.1" 200 -
2018-08-03 23:16:07,353 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:07] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:16:07,437 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:07] "POST /web/dataset/call_button HTTP/1.1" 200 -
2018-08-03 23:16:07,453 1 INFO ? werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:07] "GET /web/static/src/xml/dialog.xml?debug=1533338166117 HTTP/1.1" 200 -
2018-08-03 23:16:07,457 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:07] "POST /web/dataset/call_kw/ir.mail_server/read HTTP/1.1" 200 -
2018-08-03 23:16:07,534 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:07] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:16:09,802 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:09] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:16:09,813 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:09] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:16:19,391 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:19] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:16:19,441 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:19] "POST /web/dataset/call_kw/ir.config_parameter/load_views HTTP/1.1" 200 -
2018-08-03 23:16:19,477 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:19] "POST /web/dataset/search_read HTTP/1.1" 200 -
2018-08-03 23:16:19,636 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Mail: Fetchmail Service`.
2018-08-03 23:16:19,655 1 INFO UG odoo.addons.fetchmail.models.fetchmail: start checking for new emails on imap server web4u
2018-08-03 23:16:19,696 1 INFO UG odoo.addons.fetchmail.models.fetchmail: Fetched 0 email(s) on imap server web4u; 0 succeeded, 0 failed.
2018-08-03 23:16:21,462 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:21] "POST /web/dataset/call_kw/ir.config_parameter/read HTTP/1.1" 200 -
2018-08-03 23:16:21,509 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:21] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:16:23,344 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:23] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:16:26,814 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 23:16:26,817 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:26] "POST /web/dataset/call_kw/ir.config_parameter/write HTTP/1.1" 200 -
2018-08-03 23:16:26,835 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:26] "POST /web/dataset/call_kw/ir.config_parameter/read HTTP/1.1" 200 -
2018-08-03 23:16:26,865 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:26] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:16:26,872 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:26] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:16:28,095 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:28] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:16:28,469 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:28] "POST /web/dataset/search_read HTTP/1.1" 200 -
2018-08-03 23:16:31,350 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:31] "POST /web/dataset/call_kw/ir.config_parameter/read HTTP/1.1" 200 -
2018-08-03 23:16:31,383 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:31] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:16:32,785 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:32] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:16:36,675 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 23:16:36,677 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:36] "POST /web/dataset/call_kw/ir.config_parameter/write HTTP/1.1" 200 -
2018-08-03 23:16:36,696 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:36] "POST /web/dataset/call_kw/ir.config_parameter/read HTTP/1.1" 200 -
2018-08-03 23:16:36,728 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:36] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:16:36,743 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:36] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:16:38,246 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:38] "POST /web/dataset/search_read HTTP/1.1" 200 -
2018-08-03 23:16:51,859 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:51] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:16:52,827 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:52] "POST /web/dataset/call_kw/res.users/load_views HTTP/1.1" 200 -
2018-08-03 23:16:53,027 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:16:53] "POST /web/dataset/search_read HTTP/1.1" 200 -
2018-08-03 23:17:18,132 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:17:18] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:17:48,324 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:17:48] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:17:48,438 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:17:48] "POST /web/dataset/call_kw/res.groups/load_views HTTP/1.1" 200 -
2018-08-03 23:17:48,549 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:17:48] "POST /web/dataset/search_read HTTP/1.1" 200 -
2018-08-03 23:17:50,882 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:17:50] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:17:51,017 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:17:51] "POST /web/dataset/call_kw/res.company/load_views HTTP/1.1" 200 -
2018-08-03 23:17:51,116 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:17:51] "POST /web/dataset/search_read HTTP/1.1" 200 -
2018-08-03 23:17:52,634 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:17:52] "POST /web/dataset/call_kw/res.company/read HTTP/1.1" 200 -
2018-08-03 23:17:52,716 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:17:52] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:17:52,753 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:17:52] "GET /web/image?model=res.company&id=1&field=logo&unique=24072018004218 HTTP/1.1" 200 -
2018-08-03 23:17:55,944 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:17:55] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:18:01,726 1 INFO UG odoo.modules.registry: At least one model cache has been invalidated, signaling through the database.
2018-08-03 23:18:01,729 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:18:01] "POST /web/dataset/call_kw/res.company/write HTTP/1.1" 200 -
2018-08-03 23:18:01,785 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:18:01] "POST /web/dataset/call_kw/res.company/read HTTP/1.1" 200 -
2018-08-03 23:18:01,901 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:18:01] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:18:01,913 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:18:01] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-08-03 23:18:08,169 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:18:08] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:18:14,484 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:18:14] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:18:14,641 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:18:14] "POST /web/action/run HTTP/1.1" 200 -
2018-08-03 23:18:14,973 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:18:14] "POST /web/dataset/call_kw/crm.lead/load_views HTTP/1.1" 200 -
2018-08-03 23:18:15,140 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:18:15] "POST /web/dataset/call_kw/crm.lead/read_group HTTP/1.1" 200 -
2018-08-03 23:18:15,145 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:18:15] "POST /web/dataset/call_kw/crm.lead/read_progress_bar HTTP/1.1" 200 -
2018-08-03 23:18:15,170 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:18:15] "POST /web/dataset/call_kw/crm.stage/read HTTP/1.1" 200 -
2018-08-03 23:18:18,978 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:18:18] "POST /web/action/load HTTP/1.1" 200 -
2018-08-03 23:18:19,094 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:18:19] "POST /web/dataset/call_kw/project.project/load_views HTTP/1.1" 200 -
2018-08-03 23:18:19,208 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:18:19] "POST /web/dataset/search_read HTTP/1.1" 200 -
2018-08-03 23:18:58,204 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:18:58] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:19:48,238 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:19:48] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:20:38,276 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:20:38] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:21:19,907 1 INFO UG odoo.addons.base.ir.ir_cron: Starting job `Mail: Fetchmail Service`.
2018-08-03 23:21:20,019 1 INFO UG odoo.addons.fetchmail.models.fetchmail: start checking for new emails on imap server web4u
2018-08-03 23:21:20,060 1 INFO UG odoo.addons.fetchmail.models.fetchmail: Fetched 0 email(s) on imap server web4u; 0 succeeded, 0 failed.
2018-08-03 23:21:28,314 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:21:28] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:22:18,348 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:22:18] "POST /longpolling/poll HTTP/1.1" 200 -
2018-08-03 23:22:19,975 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:22:19] "GET / HTTP/1.1" 200 -
2018-08-03 23:23:08,377 1 INFO UG werkzeug: 172.18.0.5 - - [03/Aug/2018 23:23:08] "POST /longpolling/poll HTTP/1.1" 200 -
